packages:
  - apps/*
  - packages/*
  - docs
catalog:
  typescript: 5.7.x
catalogs:
  zod:
    zod: latest
  prisma:
    prisma: latest
    '@prisma/client': latest
  typescript:
    typescript: 5.7.X

