packages:
  - apps/*
  - packages/*
  - docs
catalog:
  typescript: 5.9.x
catalogs:
  zod:
    zod: latest
  prisma:
    prisma: latest
    '@prisma/client': latest
  typescript:
    typescript: 5.9.X
  playwright:
    '@playwright/test': 1.58.2
    '@playwright/experimental-ct-react': 1.58.2
