export const TEST_SELECTORS = {
  ACTION_BUTTONS: 'ACTION_BUTTONS',
  NUMERIC_FIELD_INCREMENT_BUTTON: 'NUMERIC_FIELD_INCREMENT_BUTTON',
  NUMERIC_FIELD_DECREMENT_BUTTON: 'NUMERIC_FIELD_DECREMENT_BUTTON',
  FEEDING_VIEW: 'FEEDING_VIEW',
  SELECTED_ACTIONS: 'ACTIONS_SELETED_ACTIONS',
  FEEDING_FORM: 'FEEDING_FORM',
};
