global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'hivepal-backend'
    scheme: http
    metrics_path: /api/metrics
    static_configs:
      - targets: ['backend:9100']