export enum EquipmentCategory {
  BOXES = 'BOXES',
  HIVE_PARTS = 'HIVE_PARTS', 
  FRAMES = 'FRAMES',
  FEEDING = 'FEEDING',
  CONSUMABLES = 'CONSUMABLES',
  TOOLS = 'TOOLS',
  PROTECTIVE = 'PROTECTIVE',
  EXTRACTION = 'EXTRACTION',
  CUSTOM = 'CUSTOM',
}