/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * Type of action performed
 */
export type ActionDtoType = typeof ActionDtoType[keyof typeof ActionDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActionDtoType = {
  FEEDING: 'FEEDING',
  TREATMENT: 'TREATMENT',
  FRAME: 'FRAME',
  OTHER: 'OTHER',
} as const;
