/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { ActionDtoType } from './actionDtoType';
import type { ActionDtoDetails } from './actionDtoDetails';

export interface ActionDto {
  /** Unique ID of the action */
  id: string;
  /** ID of the inspection this action belongs to */
  inspectionId: string;
  /** Type of action performed */
  type: ActionDtoType;
  /** Additional notes about the action */
  notes?: string;
  /** Specific details for the action */
  details: ActionDtoDetails;
}
