/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface ApiaryResponseDto {
  /** Unique identifier of the apiary */
  id: string;
  /** Name of the apiary */
  name: string;
  /**
   * Location of the apiary
   * @nullable
   */
  location?: string | null;
  /**
   * Latitude of the apiary
   * @nullable
   */
  latitude?: number | null;
  /**
   * Longitude of the apiary
   * @nullable
   */
  longitude?: number | null;
}
