/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { UserDto } from './userDto';

export interface AuthResponseDto {
  /** JWT access token */
  access_token: string;
  /** User information */
  user: UserDto;
}
