/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * Type of box
 */
export type BoxDtoType = (typeof BoxDtoType)[keyof typeof BoxDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BoxDtoType = {
  BROOD: 'BROOD',
  HONEY: 'HONEY',
  FEEDER: 'FEEDER',
} as const;
