/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * Maximum number of frames the box can hold
 * @nullable
 */
export type BoxResponseDtoMaxFrameCount = { [key: string]: unknown } | null;
