/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface ChangePasswordDto {
  /** Current password of the user */
  currentPassword: string;
  /** New password to be set for the user */
  newPassword: string;
}
