/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

export type CreateHiveDtoStatus = typeof CreateHiveDtoStatus[keyof typeof CreateHiveDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateHiveDtoStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  DEAD: 'DEAD',
  SOLD: 'SOLD',
  UNKNOWN: 'UNKNOWN',
} as const;
