/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { TreatmentActionDto } from './treatmentActionDto';

/**
 * Treatment details
 * @nullable
 */
export type CreateActionDtoTreatmentAction = TreatmentActionDto | null;
