/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface CreateInspectionObservationsDto {
  strength?: number;
  uncappedBrood?: number;
  cappedBrood?: number;
  honeyStores?: number;
  pollenStores?: number;
  queenCells?: number;
  swarmCells?: number;
  supersedureCells?: number;
  queenSeen?: boolean;
}
