/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface CreateApiaryDto {
  /** Name of the apiary */
  name: string;
  /** Location description of the apiary */
  location?: string;
  /** Latitude coordinate of the apiary */
  latitude?: number;
  /** Longitude coordinate of the apiary */
  longitude?: number;
}
