/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface CreateObservationDto {
  id?: string;
  type: string;
  numericValue?: number;
  textValue?: string;
  notes?: string;
}
