/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type CreateQueenDtoStatus = typeof CreateQueenDtoStatus[keyof typeof CreateQueenDtoStatus] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateQueenDtoStatus = {
  ACTIVE: 'ACTIVE',
  REPLACED: 'REPLACED',
  DEAD: 'DEAD',
  UNKNOWN: 'UNKNOWN',
} as const;
