/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * Optional marking, usually number or similar
 */
export type CreateQueenDtoMarking = { [key: string]: unknown };
