/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { CreateActionDtoType } from './createActionDtoType';
import type { CreateActionDtoDetails } from './createActionDtoDetails';

export interface CreateActionDto {
  /** Type of action performed */
  type: CreateActionDtoType;
  /** Additional notes about the action */
  notes?: string;
  /** Specific details for the action */
  details: CreateActionDtoDetails;
}
