/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface CreateInspectionObservationsDto {
  /**
   * Colony strength rating (typically 1-5 scale)
   * @nullable
   */
  strength?: number | null;
  /**
   * Amount of uncapped brood observed (typically 0-5 scale)
   * @nullable
   */
  uncappedBrood?: number | null;
  /**
   * Amount of capped brood observed (typically 0-5 scale)
   * @nullable
   */
  cappedBrood?: number | null;
  /**
   * Amount of honey stores observed (typically 0-5 scale)
   * @nullable
   */
  honeyStores?: number | null;
  /**
   * Amount of pollen stores observed (typically 0-5 scale)
   * @nullable
   */
  pollenStores?: number | null;
  /**
   * Number of queen cells observed
   * @nullable
   */
  queenCells?: number | null;
  /**
   * Whether swarm cells were observed
   * @nullable
   */
  swarmCells?: boolean | null;
  /**
   * Whether supersedure cells were observed
   * @nullable
   */
  supersedureCells?: boolean | null;
  /**
   * Whether the queen was observed during inspection
   * @nullable
   */
  queenSeen?: boolean | null;
}
