/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { FeedingActionDetailsDto } from './feedingActionDetailsDto';
import type { TreatmentActionDetailsDto } from './treatmentActionDetailsDto';
import type { FrameActionDetailsDto } from './frameActionDetailsDto';

/**
 * Specific details for the action
 */
export type CreateActionDtoDetails = FeedingActionDetailsDto | TreatmentActionDetailsDto | FrameActionDetailsDto;
