/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

export type FrameActionDetailsDtoType = typeof FrameActionDetailsDtoType[keyof typeof FrameActionDetailsDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FrameActionDetailsDtoType = {
  FRAME: 'FRAME',
} as const;
