/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

export type HealthControllerCheck503Details = {[key: string]: {
  status: string;
  [key: string]: unknown;
 }};
