/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type HealthControllerCheck503Error = {[key: string]: {
  status: string;
  [key: string]: unknown;
 }} | null;
