/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * Date of the most recent inspection
 * @nullable
 */
export type HiveResponseDtoLastInspectionDate = { [key: string]: unknown } | null;
