/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { HiveDetailResponseDtoStatus } from './hiveDetailResponseDtoStatus';
import type { BoxResponseDto } from './boxResponseDto';

export interface HiveDetailResponseDto {
  /** Unique identifier of the hive */
  id: string;
  /** Name of the hive */
  name: string;
  /** Status of the hive */
  status: HiveDetailResponseDtoStatus;
  /**
   * ID of the apiary this hive belongs to
   * @nullable
   */
  apiaryId?: string | null;
  /**
   * Additional notes about the hive
   * @nullable
   */
  notes?: string | null;
  /**
   * Date when the hive was installed
   * @nullable
   */
  installationDate: string | null;
  /**
   * Date of the most recent inspection
   * @nullable
   */
  lastInspectionDate?: string | null;
  /** Boxes in the hive, ordered by position from bottom to top */
  boxes: BoxResponseDto[];
}
