/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * Status of the hive
 */
export type HiveDetailResponseDtoStatus = typeof HiveDetailResponseDtoStatus[keyof typeof HiveDetailResponseDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HiveDetailResponseDtoStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  DEAD: 'DEAD',
  SOLD: 'SOLD',
  UNKNOWN: 'UNKNOWN',
} as const;
