/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * Additional notes about the hive
 * @nullable
 */
export type HiveResponseDtoNotes = { [key: string]: unknown } | null;
