/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * Date when the hive was installed
 * @nullable
 */
export type HiveResponseDtoInstallationDate = { [key: string]: unknown } | null;
