/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { QueenResponseDto } from './queenResponseDto';

/**
 * The current active queen in the hive
 * @nullable
 */
export type HiveResponseDtoActiveQueen = QueenResponseDto | null;
