/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * ID of the apiary this hive belongs to
 * @nullable
 */
export type HiveResponseDtoApiaryId = { [key: string]: unknown } | null;
