/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

export * from './createHiveDto';
export * from './createHiveDtoStatus';
export * from './createInspectionDto';
export * from './hiveResponseDto';
export * from './hiveResponseDtoStatus';
export * from './inspectionResponseDto';
export * from './inspectionsControllerFindAllParams';
export * from './updateHiveDto';
export * from './updateHiveDtoStatus';
export * from './updateInspectionDto';
