/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

export * from './boxDto';
export * from './boxDtoType';
export * from './boxResponseDto';
export * from './boxResponseDtoType';
export * from './createHiveDto';
export * from './createHiveDtoStatus';
export * from './createInspectionDto';
export * from './createInspectionObservationsDto';
export * from './createObservationDto';
export * from './createQueenDto';
export * from './hiveControllerRemove200';
export * from './hiveControllerUpdate200';
export * from './hiveDetailResponseDto';
export * from './hiveDetailResponseDtoStatus';
export * from './hiveResponseDto';
export * from './hiveResponseDtoStatus';
export * from './inspectionResponseDto';
export * from './inspectionsControllerFindAllParams';
export * from './observationResponseDto';
export * from './updateHiveBoxesDto';
export * from './updateHiveDto';
export * from './updateHiveDtoStatus';
export * from './updateInspectionDto';
export * from './updateQueenDto';