/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { FeedingActionDto } from './feedingActionDto';
import type { TreatmentActionDto } from './treatmentActionDto';
import type { FrameActionDto } from './frameActionDto';

export type InspectionResponseDtoActionsItem = FeedingActionDto | TreatmentActionDto | FrameActionDto;
