/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * Current status of the inspection
 */
export type InspectionStatus = typeof InspectionStatus[keyof typeof InspectionStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InspectionStatus = {
  SCHEDULED: 'SCHEDULED',
  OVERDUE: 'OVERDUE',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;
