/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface InspectionMetricsDto {
  /**
   * Colony strength rating
   * @nullable
   */
  strength: number | null;
  /**
   * Amount of uncapped brood observed
   * @nullable
   */
  uncappedBrood: number | null;
  /**
   * Amount of capped brood observed
   * @nullable
   */
  cappedBrood: number | null;
  /**
   * Amount of honey stores observed
   * @nullable
   */
  honeyStores: number | null;
  /**
   * Amount of pollen stores observed
   * @nullable
   */
  pollenStores: number | null;
  /**
   * Number of queen cells observed
   * @nullable
   */
  queenCells: number | null;
  /**
   * Whether swarm cells were observed
   * @nullable
   */
  swarmCells: boolean | null;
  /**
   * Whether supersedure cells were observed
   * @nullable
   */
  supersedureCells: boolean | null;
  /**
   * Whether the queen was observed during inspection
   * @nullable
   */
  queenSeen: boolean | null;
}
