/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface InspectionScoreDto {
  /** @nullable */
  populationScore: number | null;
  /** @nullable */
  queenScore: number | null;
  /** @nullable */
  storesScore: number | null;
  /** @nullable */
  overallScore: number | null;
  warnings: string[];
}
