/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { InspectionMetricsDto } from './inspectionMetricsDto';
import type { InspectionScoreDto } from './inspectionScoreDto';

export interface InspectionResponseDto {
  id: string;
  hiveId: string;
  date: string;
  /** @nullable */
  temperature?: number | null;
  /** @nullable */
  weatherConditions?: string | null;
  /** @nullable */
  notes?: string | null;
  observations: InspectionMetricsDto;
  score: InspectionScoreDto;
}
