/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface InspectionScoreDto {
  /**
   * Score for colony population and brood pattern (0-5 scale)
   * @nullable
   */
  populationScore: number | null;
  /**
   * Score for queen performance and health (0-5 scale)
   * @nullable
   */
  queenScore: number | null;
  /**
   * Score for honey and pollen stores (0-5 scale)
   * @nullable
   */
  storesScore: number | null;
  /**
   * Overall health score for the colony (0-5 scale)
   * @nullable
   */
  overallScore: number | null;
  /** List of warnings or issues detected during inspection */
  warnings: string[];
}
