/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface LoginDto {
  /** User email address used for login */
  email: string;
  /**
   * User password
   * @minLength 6
   */
  password: string;
}
