/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface ObservationResponseDto {
  /** @nullable */
  strength: number | null;
  /** @nullable */
  uncappedBrood: number | null;
  /** @nullable */
  cappedBrood: number | null;
  /** @nullable */
  honeyStores: number | null;
  /** @nullable */
  pollenStores: number | null;
  /** @nullable */
  queenCells: number | null;
  /** @nullable */
  swarmCells: number | null;
  /** @nullable */
  supersedureCells: number | null;
  queenSeen?: boolean;
}
