/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface ObservationResponseDto {
  id: string;
  inspectionId: string;
  type: string;
  /** @nullable */
  numericValue?: number | null;
  /** @nullable */
  textValue?: string | null;
  /** @nullable */
  notes?: string | null;
}
