/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type QueenResponseDtoStatus =
  | (typeof QueenResponseDtoStatus)[keyof typeof QueenResponseDtoStatus]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const QueenResponseDtoStatus = {
  ACTIVE: 'ACTIVE',
  REPLACED: 'REPLACED',
  DEAD: 'DEAD',
  UNKNOWN: 'UNKNOWN',
} as const;
