/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * Current status of the queen
 */
export type QueenStatus = typeof QueenStatus[keyof typeof QueenStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const QueenStatus = {
  ACTIVE: 'ACTIVE',
  REPLACED: 'REPLACED',
  DEAD: 'DEAD',
  UNKNOWN: 'UNKNOWN',
} as const;
