/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Hive-Pal API
 * API documentation for the Hive-Pal application
 * OpenAPI spec version: 1.0
 */

export type QueenResponseDtoSource = { [key: string]: unknown };
