/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { QueenResponseDtoStatus } from './queenResponseDtoStatus';

export interface QueenResponseDto {
  id: string;
  /** @nullable */
  hiveId?: string | null;
  /** @nullable */
  marking: string | null;
  /** @nullable */
  color: string | null;
  year: number;
  /** @nullable */
  source?: string | null;
  /** @nullable */
  status?: QueenResponseDtoStatus;
  /** @nullable */
  installedAt?: string | null;
  /** @nullable */
  replacedAt?: string | null;
}
