/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface RegisterDto {
  /** User email address */
  email: string;
  /**
   * User password
   * @minLength 6
   */
  password: string;
  /** User display name (optional) */
  name?: string;
}
