/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface ResetPasswordDto {
  /** Temporary password to be set for the user */
  tempPassword: string;
}
