/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface TreatmentActionDetailsDto {
  /** Treatment product name */
  product: string;
  /** Treatment quantity */
  quantity: number;
  /** Unit of measurement */
  unit: string;
  /** Treatment duration */
  duration?: string;
}
