/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface TreatmentActionDto {
  /** Treatment product name (Apivar, Formic Pro, etc.) */
  product: string;
  /** Quantity of treatment */
  quantity: number;
  /** Unit of measurement (strips, pads, grams, ml) */
  unit: string;
  /** Duration of treatment (7 days, 14 days, etc.) */
  duration?: string;
}
