/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * Type of action
 */
export type TreatmentActionDetailsDtoType = typeof TreatmentActionDetailsDtoType[keyof typeof TreatmentActionDetailsDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TreatmentActionDetailsDtoType = {
  TREATMENT: 'TREATMENT',
} as const;
