/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * Optional color of the queen
 */
export type UpdateQueenDtoColor = { [key: string]: unknown };
