/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { CreateInspectionObservationsDto } from './createInspectionObservationsDto';
import type { InspectionStatus } from './inspectionStatus';

export interface UpdateInspectionDto {
  /** ID of the inspection to update */
  id?: string;
  /** ID of the hive being inspected */
  hiveId?: string;
  /** Date when the inspection was performed */
  date?: string;
  /**
   * Temperature during inspection (in celsius)
   * @nullable
   */
  temperature?: number | null;
  /**
   * Weather conditions during inspection
   * @nullable
   */
  weatherConditions?: string | null;
  /**
   * Additional notes about the inspection
   * @nullable
   */
  notes?: string | null;
  /** Observations and metrics recorded during inspection */
  observations?: CreateInspectionObservationsDto;
  /** Current status of the inspection */
  status: InspectionStatus;
}
