/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { QueenStatus } from './queenStatus';

/**
 * Current status of the queen
 * @nullable
 */
export type UpdateQueenDtoStatus = QueenStatus | null;
