/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * Current status of the hive
 */
export type UpdateHiveDtoStatus = typeof UpdateHiveDtoStatus[keyof typeof UpdateHiveDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateHiveDtoStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  DEAD: 'DEAD',
  SOLD: 'SOLD',
  UNKNOWN: 'UNKNOWN',
  ARCHIVED: 'ARCHIVED',
} as const;
