/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { BoxDto } from './boxDto';

export interface UpdateHiveBoxesDto {
  /** List of boxes for the hive (will replace existing boxes) */
  boxes: BoxDto[];
}
