/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { UpdateHiveDtoStatus } from './updateHiveDtoStatus';

export interface UpdateHiveDto {
  /** The name of the hive */
  name?: string;
  /** The ID of the apiary this hive belongs to */
  apiaryId?: string;
  /** Additional notes about the hive */
  notes?: string;
  /** Date when the hive was installed */
  installationDate?: string;
  /** Current status of the hive */
  status?: UpdateHiveDtoStatus;
}
