/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * Role of the user
 */
export type UserResponseDtoRole =
  (typeof UserResponseDtoRole)[keyof typeof UserResponseDtoRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserResponseDtoRole = {
  USER: 'USER',
  ADMIN: 'ADMIN',
} as const;
