/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { UserDtoRole } from './userDtoRole';

export interface UserDto {
  /** User ID */
  id: string;
  /** User email */
  email: string;
  /** User display name */
  name?: string;
  /** User role */
  role: UserDtoRole;
  /** Whether the user needs to change their password */
  passwordChangeRequired: boolean;
}
