/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * Name of the user
 */
export type UserResponseDtoName = { [key: string]: unknown };
