/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * API Example
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { UserResponseDtoRole } from './userResponseDtoRole';

export interface UserResponseDto {
  /** Unique identifier for the user */
  id: string;
  /** Email address of the user */
  email: string;
  /**
   * Name of the user
   * @nullable
   */
  name?: string | null;
  /** Role of the user */
  role: UserResponseDtoRole;
  /** Whether the user needs to change their password */
  passwordChangeRequired: boolean;
  /** User creation date */
  createdAt: string;
  /** Last update date */
  updatedAt: string;
}
